# Add new HPC Best Practices webinar event from ideas-productivity.org site
name: "HPC-BP: add new event from ideas-productivity.org"

on:
  workflow_dispatch:
    inputs:
      event-file:
        description: 'Basename of HPC-BP event on ideas-productivity.org (without extension)'
        required: true
        type: string

jobs:
  hpcbp-cc-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # - name: Check the file is there
      #   run: |
      #     ls -l Events/${{ inputs.event-file }}.md || :

      - name: Download the new curated content article
        uses: carlosperate/download-file-action@v2
        with:
          file-url: https://ideas-productivity.org/internal/events-hpcbp-bsswio/${{ inputs.event-file }}
          location: 'Events'
          file-name: ${{ inputs.event-file }}.md

      # - name: Check the file is there
      #   run: |
      #     ls -l Events/${{ inputs.event-file }}.md || :

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          title: Add new HPC-BP webinar event
          branch: ${{ github.actor }}-hpcbp-new-event
          branch-suffix: timestamp
          assignees: ${{ github.actor }}
          commit-message: "Adding new HPC-BP webinar event from the ideas-productivity.org website"
          body: "Adding new HPC-BP webinar event from the ideas-productivity.org website"
          labels: |
            content: event

      - name: Check PR results
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Get PR ID
        id: pr-id
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_id=$(gh pr view ${{ steps.cpr.outputs.pull-request-url }} --json id --jq ".id")
          echo Pull request id = $pr_id
          echo "pr-id=$pr_id" >> $GITHUB_OUTPUT

      - name: Check PR ID
        run: |
          echo "Pull Request ID - ${{ steps.pr-id.outputs.pr-id }}"

      - name: Find the target project and column we want to add the PR to
        id: project-info
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          proj_id=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/bernhold/bssw.io-bernhold/projects --jq ".[] | select(.name == \"Content Development\") | .id")
          col_id=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /projects/$proj_id/columns --jq ".[] | select(.name == \"Ready for digest\") | .id")
          echo Project board id = $proj_id
          echo Column id = $col_id
          echo "proj_id=$proj_id" >> $GITHUB_OUTPUT
          echo "col_id=$col_id" >> $GITHUB_OUTPUT

      # - name: Merge PR
      #   if: ${{ steps.cpr.outputs.pull-request-number }}
      #   env:
      #     GH_TOKEN: ${{ secrets.PR_MERGE_PAT }}
      #   run: |
      #     gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --auto --body "Automatically merging script-generated event"
            