# Add new HPC Best Practices webinar event from ideas-productivity.org site
name: Add new hpcbp event from ideas-productivity.org

on:
  workflow_dispatch:
    inputs:
      event-file:
        description: 'Basename of HPC-BP event on ideas-productivity.org (without extension)'
        required: true
        type: string

jobs:
  hpcbp-cc-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Check the file is there
        run: |
          ls -l Events/${{ inputs.event-file }}.md || :

      - name: Download the new curated content article
        uses: carlosperate/download-file-action@v2
        with:
          file-url: https://ideas-productivity.org/internal/events-hpcbp-bsswio/${{ inputs.event-file }}
          location: 'Events'
          file-name: ${{ inputs.event-file }}.md

      - name: Check the file is there
      run: |
        ls -l Events/${{ inputs.event-file }}.md || :

      # - name: Create pull request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     title: Update HPC-BP webinar curated content
      #     branch: ${{ github.actor }}-hpcbp-webinars-cc-update
      #     branch-suffix: timestamp
      #     assignees: ${{ github.actor }}
      #     commit-message: "Updating HPC-BP webinar curated content from the ideas-productivity.org website"
      #     body: "Updating HPC-BP webinar curated content from the ideas-productivity.org website"
      #     labels: |
      #       content: curated
      #       content: updates
            