# Update HPC Best Practices webinar series curated content from ideas-productivity.org site
name: Create PR to update hpcbp-webinars-cc article

on:
  workflow_dispatch:

jobs:
  hpcbp-cc-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # - name: Check the file is there
      #   run: |
      #     ls -l CuratedContent/hpcbp-webinars-cc.md
      #     cp CuratedContent/hpcbp-webinars-cc.md CuratedContent/hpcbp-webinars-cc.md.bak

      - name: Download the new curated content article
        uses: carlosperate/download-file-action@v2
        with:
          file-url: https://ideas-productivity.org/internal/hpcbp-webinars/hpcbp-webinars-cc.md
          location: 'CuratedContent'
          file-name: hpcbp-webinars-cc.md

      # - name: Check that the file has been updated
      #   run: |
      #     ls -l CuratedContent/hpcbp-webinars-cc.md
      #     diff -c CuratedContent/hpcbp-webinars-cc.md CuratedContent/hpcbp-webinars-cc.md.bak || :

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
